### ISSUE TITLE
요구사항명세서

### ISSUE THREAD

**Issue by choiyaeman** [choiyaeman/First-Project#1]
### 요구사항명세서 작성해주세요.

> 

- _2020-04-20~04-23_

**Comment by choiyaeman** [comment]
@choiyaeman 님이 알려준 이슈입니다.

**Comment by choiyaeman** [comment]
이 작업이 끝나면 @choiyaeman 님에게 알려주세요.

**Comment by 2eYJ** [comment]
명세서 다운이 안되는데 권한이 막혀 있는건가요?

**Comment by choiyaeman** [comment]
권한 주었습니다

**Comment by choiyaeman** [comment]
요구사항명세서 작성 완료
